# Dashboard de Previsões Macroeconômicas - Configuração para Streamlit Cloud
# Este arquivo contém configurações específicas para o deploy no Streamlit Cloud.

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
